# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers-legacy
        environment:
          MAX_HEAP_SIZE: 2048m
          HEAP_NEWSIZE: 512m

    steps:
      - checkout
      # Download and cache dependencies.
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          command: npm install

      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      # run tests!
      - run:
          command: npm test
